from config.env import env


#OBJECT STORAGE CONFIG
# AWS
DEFAULT_FILE_STORAGE = env("DEFAULT_FILE_STORAGE")
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
AWS_S3_ENDPOINT_URL = env("AWS_S3_ENDPOINT_URL")
AWS_QUERYSTRING_AUTH = env("AWS_QUERYSTRING_AUTH", default=False, cast=bool)
AWS_S3_FILE_OVERWRITE = env("AWS_S3_FILE_OVERWRITE", default=False, cast=bool)
AWS_DEFAULT_ACL = env("AWS_DEFAULT_ACL")
AWS_SERVICE_NAME = env("AWS_SERVICE_NAME")