# Generated by Django 4.0.7 on 2024-03-31 12:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import gallery.utils.models_path_aws


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to=gallery.utils.models_path_aws.path_media_file)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
