# Generated by Django 4.0.7 on 2024-04-01 11:54

import django.contrib.postgres.fields
from django.db import migrations, models
import gallery.utils.models_path_aws


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=gallery.utils.models_path_aws.path_media_file),
        ),
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
    ]
