# Generated by Django 4.0.7 on 2024-04-01 12:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gallery.utils.models_path_aws


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0003_alter_media_description_alter_media_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=gallery.utils.models_path_aws.path_media_file)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medias', to='mediahub.file'),
        ),
    ]
