# Generated by Django 4.0.7 on 2024-04-01 14:07

from django.db import migrations, models
import gallery.utils.models_path_aws


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0004_file_alter_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=gallery.utils.models_path_aws.path_media_file),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
